### ISSUE TITLE
Unknown props warning with React 15.3.0

### ISSUE THREAD

**Issue by jamieparkinson** [ameyms/react-animated-number#4]
Using the plugin with React 15.3.0, I get the following warning in the console:

`Warning: Unknown props formatValue, stepPrecision, duration, component, frameStyle on <span> tag`

A brief Google suggests this kind of warning is common with recent versions of React. However, I easily fixed it for my use case by changing the 3rd arg of `createElement` from `this.props` to `{}`, on line 152 of AnimatedNumber.js. So far as I can see this will have no adverse side effects.

**Comment by ameyms** [comment]
Unfortunately, the fix isn't that straightforward.
`this.props` is being passed to `createElement` because we need to transfer props like even handlers and `data-*` attributes to the underlying node that contains the number.

We will need to manually filter out invalid props.

**Comment by ameyms** [comment]
_For posterity:_
This was fixed by [filtering out props](https://github.com/ameyms/react-animated-number/blob/f57707bb84cee7a8910d5e163bec05382498a821/src/AnimatedNumber.jsx#L160-L170) that are defined in the [component's propTypes](https://github.com/ameyms/react-animated-number/blob/f57707bb84cee7a8910d5e163bec05382498a821/src/AnimatedNumber.jsx#L29-L38). 

Need to find a more reliable way of doing this.
